### ISSUE TITLE
"Run" and "Result" view not consistent

### ISSUE THREAD

**Issue by rdewijn** [tercen/vsn_shiny_operator#5]
The way/order in which the run and result view are presented to the user are not consistent when running the operator in a data step for the first time and when re-running between reset / run.

Also, change such that user has the option not to switch to result view before returning data to Bionavigator => more logical

**Comment by ginberg** [comment]
I have added the upload button in the run view as well (version 0.0.2)

I can't fix the the issue about the inconsistent view right now. It has to do with how the results are stored in Tercen and that these are not removed when resetting the operator. Any idea @fnaji @amaurel how we could solve this?

**Comment by ginberg** [comment]
@rdewijn this inconsistency should be fixed now in the [latest version](https://tercen.com/pamgene/w/6a2eb513feba11bce422a5026520cbc5). I am using the tercen mode parameter to determine the view, so after resetting the step the user is not going to the result view anymore. I did remove the switch to result button since it doesn't work well with the mode. After uploading the data to Tercen, the user can go to the Computed Tables view. When going back to the Operator view,  the user can view the result of the calculation.

**Comment by rdewijn** [comment]
Yes, this works. Maybe add a remark in teh interface that the user has to press "run" in Tercen before the shiny becomes fully active?

**Comment by ginberg** [comment]
Nice it works. Yes, I can add a message in case the user is in "view" modus, so he/she knows how to get started
