### ISSUE TITLE
Are both the "run" and "transform data" button necessary

### ISSUE THREAD

**Issue by rdewijn** [tercen/vsn_shiny_operator#8]
Seems like double action in this case. run and transform after pressing the run button?

**Comment by ginberg** [comment]
hi @rdewijn, I added the transform data button later when I found out that we needed to update the state of the operator in Tercen. The "Run" saves the result of the calculation itself. We can do both actions when pressing the "Run", do you want that? I think it makes sense in this case, since you have to do both actions in order to see the result

**Comment by rdewijn** [comment]
Yes, I think that makes most sense

**Comment by ginberg** [comment]
Ok, I have updated the code. The updated operator can be found in the [tercen workflow](https://tercen.com/pamgene/w/6a2eb513feba11bce422a5026520cbc5/ds/844adac4-7113-4d74-b53a-0c2e32bc8296) Does this work well for you?
